name: CI/CD Devows - Frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dnf-frontend/**'
jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build imagen Frontend y push a ECR
        run: |
          cd Dnf-frontend
          docker build -t devows-project-frontend .
          docker tag devows-project-frontend:latest 563092261209.dkr.ecr.us-east-1.amazonaws.com/devows-project-frontend:latest
          docker push 563092261209.dkr.ecr.us-east-1.amazonaws.com/devows-project-frontend:latest
          
      - name: Descargar Task Definition actual
        run: |
          aws ecs describe-task-definition \
            --task-definition devows-project-frontend \
            --query taskDefinition > task-definition.json
            
      - name: Actualizar Tag de la imagen en la Task Def
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: frontend
          image: 563092261209.dkr.ecr.us-east-1.amazonaws.com/devows-project-frontend:latest
          
      - name: Desplegar nueva Task Definition en el Servicio
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: devows-project-frontend-service
          cluster: devows-project-cluster
          wait-for-service-stability: true
